import CmsNavbar from '@/components/Header/CmsNavbar';
import './globals.css';

export const metadata = {
  title: 'Safe Movers Sanity Studio',
  description: 'Generated by Sanity ft SafeMovers',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CmsNavbar />
        {children}
      </body>
    </html>
  );
}
